# -*- coding: utf-8 -*-
"""cleaned_sugar_cosmetics_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17fTAcTroMVZZ0Q-uqWW95NrPsvWzxbn7
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Step 1: Install and import libraries
import pandas as pd

# Step 2: Mount Google Drive (skip if uploading file manually)
from google.colab import files
uploaded = files.upload()   # choose your sugar_cosmetics_instagram_data.csv file

# Step 3: Load dataset
df = pd.read_csv("/content/sugar_cosmetics_instagram_data - sugar_cosmetics_instagram_data.csv.csv")

# Step 4: Basic info
print("Dataset shape:", df.shape)
df.head()

# Check column names and missing values
df.info()
print("\nMissing values:\n", df.isnull().sum())

df.columns

import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("/content/sugar_cosmetics_instagram_data - sugar_cosmetics_instagram_data.csv (1).csv")

# Clean column names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

# Confirm columns
print(df.columns)

# Convert post_date to datetime
df['post_date'] = pd.to_datetime(df['post_date'], errors='coerce')

# Drop duplicates
df.drop_duplicates(inplace=True)

# Fill missing numeric columns
numeric_cols = ['likes', 'comments', 'shares', 'saves', 'reach', 'impressions', 'profile_visits', 'follows']
df[numeric_cols] = df[numeric_cols].fillna(0)

# Fill text columns
text_cols = ['post_type', 'campaign_type', 'hashtags', 'audience_emotion', 'engagement_source']
for col in text_cols:
    df[col] = df[col].fillna('').astype(str)

# Feature engineering
df['month_year'] = df['post_date'].dt.to_period('M').astype(str)
df['day_of_week'] = df['post_date'].dt.day_name()

# Engagement Rate formula
df['engagement_rate'] = (df['likes'] + df['comments'] + df['shares'] + df['saves']) / df['reach'].replace(0, np.nan)

# Preview
df.head()

import matplotlib.pyplot as plt
import seaborn as sns

# Group by month-year and count posts
monthly_posts = df.groupby('month_year').size().reset_index(name='post_count')

# Sort by date
monthly_posts['month_year'] = pd.to_datetime(monthly_posts['month_year'])
monthly_posts = monthly_posts.sort_values('month_year')

# Plot trend
plt.figure(figsize=(10,5))
sns.lineplot(data=monthly_posts, x='month_year', y='post_count', marker='o')
plt.title("Monthly Posting Trend - Sugar Cosmetics")
plt.xlabel("Month")
plt.ylabel("Number of Posts")
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

# Top 10 posts by Likes
top_likes = df.sort_values(by='likes', ascending=False).head(10)

plt.figure(figsize=(10,6))
sns.barplot(data=top_likes, x='likes', y='post_type', hue='campaign_type', dodge=False)
plt.title("Top 10 Posts by Likes")
plt.xlabel("Likes")
plt.ylabel("Post Type")
plt.legend(title='Campaign Type')
plt.show()

# Top 10 posts by Engagement Rate
top_engagement = df.sort_values(by='engagement_rate', ascending=False).head(10)

plt.figure(figsize=(10,6))
sns.barplot(data=top_engagement, x='engagement_rate', y='post_type', hue='campaign_type', dodge=False)
plt.title("Top 10 Posts by Engagement Rate")
plt.xlabel("Engagement Rate")
plt.ylabel("Post Type")
plt.legend(title='Campaign Type')
plt.show()

# Aggregate average metrics by post_type
post_perf = df.groupby('post_type')[['likes', 'comments', 'shares', 'saves', 'engagement_rate']].mean().reset_index()

# Plot
plt.figure(figsize=(10,6))
sns.barplot(data=post_perf, x='post_type', y='engagement_rate')
plt.title("Average Engagement Rate by Post Type")
plt.xlabel("Post Type")
plt.ylabel("Avg Engagement Rate")
plt.show()

# Average engagement by weekday
day_engagement = df.groupby('day_of_week')['engagement_rate'].mean().reset_index()

# Order the days properly
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
day_engagement['day_of_week'] = pd.Categorical(day_engagement['day_of_week'], categories=day_order, ordered=True)
day_engagement = day_engagement.sort_values('day_of_week')

# Plot
plt.figure(figsize=(10,6))
sns.barplot(data=day_engagement, x='day_of_week', y='engagement_rate')
plt.title("Average Engagement Rate by Day of Week")
plt.xlabel("Day")
plt.ylabel("Avg Engagement Rate")
plt.xticks(rotation=45)
plt.show()

# Calculate average funnel metrics
funnel_data = {
    'Metric': ['Impressions', 'Reach', 'Likes', 'Comments', 'Shares', 'Saves'],
    'Average': [
        df['impressions'].mean(),
        df['reach'].mean(),
        df['likes'].mean(),
        df['comments'].mean(),
        df['shares'].mean(),
        df['saves'].mean()
    ]
}

funnel_df = pd.DataFrame(funnel_data)

# Plot funnel as horizontal bar chart
plt.figure(figsize=(8,6))
sns.barplot(data=funnel_df, y='Metric', x='Average')
plt.title("Engagement Funnel - Average User Actions")
plt.xlabel("Average Count")
plt.ylabel("Interaction Type")
plt.show()

# Explode hashtags into individual tags
df['hashtags'] = df['hashtags'].str.replace('#', '').str.split(',')
hashtags_exploded = df.explode('hashtags')

# Clean up and group
hashtags_exploded['hashtags'] = hashtags_exploded['hashtags'].str.strip().str.lower()
hashtag_perf = hashtags_exploded.groupby('hashtags')['engagement_rate'].mean().reset_index()

# Get top 10 hashtags
top_hashtags = hashtag_perf.sort_values(by='engagement_rate', ascending=False).head(10)

# Plot
plt.figure(figsize=(10,6))
sns.barplot(data=top_hashtags, x='engagement_rate', y='hashtags')
plt.title("Top 10 Hashtags by Engagement Rate")
plt.xlabel("Avg Engagement Rate")
plt.ylabel("Hashtag")
plt.show()

df.to_csv("/content/cleaned_sugar_cosmetics_data.csv", index=False)
print("✅ Cleaned data exported successfully!")